export type Locale = "en" | "fa";
export type ProjectSlug = "apex" | "vibe" | "mrm" | "first-choice";

export const projects = {
  apex: {
    accent: "green",
    cover: "/projects/apex/new/app-dashboard.jpg",
    images: [
      { src: "/projects/apex/new/marketing-home.jpg", en: "Public positioning and live market read", fa: "معرفی محصول و تحلیل زنده بازار" },
      { src: "/projects/apex/new/analysis-builder.jpg", en: "Market, timeframe, and analysis-mode configuration", fa: "انتخاب بازار، بازه زمانی و نوع تحلیل" },
      { src: "/projects/apex/new/analysis-history.jpg", en: "Analysis history with confidence and market context", fa: "تاریخچه تحلیل ها همراه با اطمینان و شرایط بازار" },
      { src: "/projects/apex/new/credit-model.jpg", en: "Prepaid credit model and transparent usage costs", fa: "مدل اعتباری و هزینه شفاف استفاده" },
      { src: "/projects/apex/new/command-palette.jpg", en: "Command palette for urgent actions", fa: "دسترسی سریع به عملیات مهم" },
    ],
    en: {
      title: "Apex",
      eyebrow: "Live AI product · 2025-present",
      summary: "Market intelligence without the analysis overload.",
      short: "A live, monetized AI market-analysis product grounded in deterministic algorithms and real multi-source data.",
      role: "AI Product Manager · Product Designer · Full-stack builder",
      problem: "Traders face too many indicators, conflicting analysts, and emotionally charged decisions. Generic AI adds prose, but it does not add a reliable analytical foundation.",
      approach: "I translated market logic developed over several years from Pine Script into Python. Apex processes live data first, then gives a smaller LLM structured evidence to explain in clear human language.",
      result: "A live credit-based product covering four asset classes, with decisive output in about 30 seconds and approximately 95% lower LLM spend.",
      metrics: ["~95% lower LLM spend", "4 asset classes", "~30 sec structured reads", "500+ crypto pairs"],
      decisions: [
        ["Algorithms before language", "Deterministic preprocessing does the analytical work; the LLM explains structured evidence instead of guessing from raw data."],
        ["High-value inference only", "Always-on content uses rule-based NLG at near-zero model cost. Paid inference is reserved for deeper, on-demand analysis."],
        ["Clarity over terminal complexity", "The product gives a verdict, rationale, levels, trade plan, and counter-case instead of another wall of indicators."],
        ["Support emotional moments", "A dedicated Panic Button helps users step back and reassess a position when urgency can override judgment."],
      ],
      contribution: ["Product thesis, roadmap, pricing, and launch", "End-to-end UX and interface design", "Prompt architecture, guardrails, and output format", "Python/FastAPI data and analysis services", "React/TypeScript frontend and production deployment"],
    },
    fa: {
      title: "Apex",
      eyebrow: "محصول فعال مبتنی بر هوش مصنوعی · ۱۴۰۴ تا امروز",
      summary: "تحلیل بازار، بدون سردرگمی میان ابزارها و نظرهای متناقض.",
      short: "محصول فعال و درآمدزای تحلیل بازار که هوش مصنوعی را روی الگوریتم های مشخص و داده های واقعی چندمنبعی به کار می گیرد.",
      role: "مدیر محصول هوش مصنوعی · طراح محصول · توسعه دهنده تمام پشته",
      problem: "معامله گرها با تعداد زیادی اندیکاتور، تحلیل های متناقض و تصمیم های احساسی روبه رو هستند. یک هوش مصنوعی عمومی می تواند متن تولید کند، اما پایه تحلیلی قابل اتکایی ندارد.",
      approach: "منطق تحلیلی چندساله ام را از Pine Script به Python منتقل کردم. Apex ابتدا داده زنده را با این الگوریتم ها پردازش می کند و بعد شواهد ساختاریافته را برای توضیحی روشن به یک LLM سبک تر می دهد.",
      result: "محصولی فعال با مدل اعتباری، پوشش چهار کلاس دارایی، خروجی حدود ۳۰ ثانیه ای و نزدیک به ۹۵ درصد کاهش هزینه LLM.",
      metrics: ["حدود ۹۵٪ کاهش هزینه LLM", "۴ کلاس دارایی", "خروجی حدود ۳۰ ثانیه", "بیش از ۵۰۰ جفت رمزارز"],
      decisions: [
        ["الگوریتم پیش از زبان", "پردازش قطعی کار تحلیلی را انجام می دهد و LLM به جای حدس زدن از داده خام، شواهد ساختاریافته را توضیح می دهد."],
        ["استفاده از LLM فقط جایی که ارزش دارد", "محتوای روزانه با منطق قطعی و تقریبا بدون هزینه مدل تولید می شود؛ تحلیل عمیق و درخواستی از LLM استفاده می کند."],
        ["وضوح به جای پیچیدگی", "محصول به جای انبوهی از اندیکاتورها، نتیجه، دلیل، سطوح مهم، برنامه معامله و سناریوی مخالف را نشان می دهد."],
        ["کمک در لحظه های احساسی", "دکمه پنیک به کاربر کمک می کند وقتی فشار تصمیم بالا می رود، یک بار دیگر موقعیت خود را منطقی بررسی کند."],
      ],
      contribution: ["استراتژی محصول، نقشه راه، قیمت گذاری و لانچ", "طراحی کامل تجربه و رابط کاربری", "معماری پرامپت، گاردریل و ساختار خروجی", "سرویس های داده و تحلیل با Python و FastAPI", "فرانت اند React و TypeScript و استقرار محصول"],
    },
  },
  vibe: {
    accent: "blue",
    cover: "/projects/vibe/new/business-dashboard.jpg",
    images: [
      { src: "/projects/vibe/new/discovery-home.jpg", en: "Discovery experience built around the reviewer, not only the score", fa: "تجربه کشف بر اساس نویسنده نظر، نه فقط امتیاز" },
      { src: "/projects/vibe/new/ai-review-system.jpg", en: "AI-assisted review quality with the final decision left to the user", fa: "کنترل کیفیت نظر با هوش مصنوعی و تصمیم نهایی کاربر" },
      { src: "/projects/vibe/new/identity-verification.jpg", en: "Optional identity verification and its product rationale", fa: "احراز هویت اختیاری و توضیح روشن دلیل آن" },
      { src: "/projects/vibe/new/review-transparency.jpg", en: "Reviewer history, verification, and business replies", fa: "سابقه نویسنده، احراز هویت و پاسخ کسب و کار" },
      { src: "/projects/vibe/new/trust-layers.jpg", en: "The three-layer trust model", fa: "مدل سه لایه اعتماد" },
    ],
    en: {
      title: "Vibe",
      eyebrow: "Pre-launch marketplace · 2023-present",
      summary: "A local discovery product built around credible reviews.",
      short: "A two-sided business discovery and reputation platform designed for trustworthy decisions, fair visibility, and operational readiness.",
      role: "Technical Product Lead · Senior Frontend Engineer · UX/UI Designer",
      problem: "People relied on influencer content and scattered social posts to judge local businesses. Good businesses lacked a credible, regional reputation layer where real customer experience could compound over time.",
      approach: "I defined trustworthy reviews and useful business profiles as the core loop, then layered discovery, safety, operations, and monetization around that value. I designed the complete UX and built the customer and business frontend from zero.",
      result: "A launch-ready product foundation spanning customer, business-owner, and admin workflows, backed by formal QA, traceability, risk audits, and moderation design.",
      metrics: ["1.4MB → 165kB main bundle", "32 auth test cases", "22 traced requirements", "8 technical handoff specs"],
      decisions: [
        ["Trust before monetization", "Reviews, profiles, and discovery came first. Packages followed only after the product's real value and business willingness to pay were clearer."],
        ["Suggest, never overwrite", "AI can flag a rating-tone mismatch and explain a one-star recommendation. The user's original rating changes only with explicit consent."],
        ["Verification without a wall", "KYC is optional and its benefit is visible. Review credibility can also be assessed through anti-fraud patterns, keeping the core flow accessible."],
        ["One operational picture", "Moderation brings users, businesses, reviews, evidence, appeals, and risk into a shared admin workflow with explicit states."],
      ],
      contribution: ["Product concept, roadmap, and feature prioritization", "Complete RTL UX/UI and design system", "Customer and business frontend from zero", "API contracts and backend handoff specifications", "QA strategy, defect triage, and launch-readiness audits", "Trust, safety, KYC, and moderation product design"],
    },
    fa: {
      title: "Vibe",
      eyebrow: "مارکت پلیس در آستانه لانچ · ۱۴۰۲ تا امروز",
      summary: "کشف کسب و کارهای محلی بر پایه نظرهای قابل اعتماد.",
      short: "پلتفرم دوسویه معرفی و اعتبارسنجی کسب و کارها برای تصمیم بهتر کاربران، دیده شدن منصفانه و مدیریت عملیاتی از روز اول.",
      role: "رهبر فنی محصول · توسعه دهنده ارشد فرانت اند · طراح تجربه و رابط کاربری",
      problem: "برای شناخت کسب و کارهای محلی، مردم بیشتر به اینفلوئنسرها و محتوای پراکنده شبکه های اجتماعی متکی بودند. کسب و کارهای خوب هم جای قابل اتکایی برای ساختن اعتبار واقعی نداشتند.",
      approach: "نظرهای معتبر و پروفایل کاربردی کسب و کار را هسته محصول قرار دادم و کشف، ایمنی، عملیات و درآمدزایی را در لایه های بعدی چیدم. تمام تجربه کاربری را طراحی کردم و فرانت اند کاربران و صاحبان کسب و کار را از صفر ساختم.",
      result: "زیرساخت آماده لانچ برای کاربر، صاحب کسب و کار و ادمین، همراه با تست های رسمی، ردیابی نیازمندی ها، بررسی ریسک و طراحی کامل رسیدگی به تخلف.",
      metrics: ["کاهش باندل اصلی از ۱.۴ مگابایت به ۱۶۵ کیلوبایت", "۳۲ تست احراز هویت", "۲۲ نیازمندی قابل ردیابی", "۸ سند تحویل فنی"],
      decisions: [
        ["اعتماد پیش از درآمدزایی", "نظرها، پروفایل ها و کشف کسب و کار در اولویت بودند. بسته های تجاری زمانی وارد نقشه راه شدند که ارزش واقعی محصول روشن تر شد."],
        ["پیشنهاد، نه تغییر اجباری", "هوش مصنوعی می تواند ناهماهنگی متن و امتیاز را توضیح دهد و حداکثر یک ستاره پیشنهاد تغییر بدهد؛ تصمیم نهایی همیشه با کاربر است."],
        ["احراز هویت بدون اجبار", "KYC اختیاری است و مزیت آن شفاف توضیح داده می شود. الگوهای ضدتقلب هم به سنجش اعتبار کمک می کنند تا مسیر اصلی ساده بماند."],
        ["تصویر عملیاتی یکپارچه", "رسیدگی به کاربران، کسب و کارها، نظرها، مدارک، اعتراض ها و ریسک در یک جریان مدیریتی با وضعیت های مشخص انجام می شود."],
      ],
      contribution: ["ایده محصول، نقشه راه و اولویت بندی", "طراحی کامل تجربه راست چین و سیستم طراحی", "ساخت فرانت اند کاربر و کسب و کار از صفر", "قراردادهای API و اسناد تحویل به بک اند", "برنامه تست، اولویت بندی باگ و بررسی آمادگی لانچ", "طراحی محصول برای اعتماد، ایمنی، KYC و رسیدگی"],
    },
  },
  mrm: {
    accent: "amber",
    images: [],
    en: {
      title: "MRM",
      eyebrow: "Business continuity tool · 2025",
      summary: "A working product built for an internet shutdown.",
      short: "An offline-first coordination system that kept a 40-person company working during connectivity loss in wartime.",
      role: "Product Owner · Designer · Engineer",
      problem: "During the first days of war in Iran, internet access disappeared and the company could not rely on its normal cloud tools. Work stopped because coordination itself depended on connectivity.",
      approach: "I reduced the problem to its operational essentials and built a local-network tool that did not depend on the public internet. The priority was continuity and low-friction adoption, not a broad feature set.",
      result: "Approximately 40 people used MRM during the shutdowns until internet service returned, allowing essential work and coordination to continue.",
      metrics: ["~40 active users", "Built during shutdown", "Local-network operation", "Used until connectivity returned"],
      decisions: [
        ["Constraint-led scope", "Every feature had to justify itself against one question: does this help the team keep working without internet?"],
        ["Familiar over novel", "Under pressure, adoption matters more than feature sophistication. The interaction model stayed direct and recognizable."],
        ["Local resilience", "The product removed dependence on public cloud availability for the essential coordination path."],
      ],
      contribution: ["Problem framing under operational pressure", "Rapid scope and workflow design", "End-to-end product implementation", "Deployment and adoption for a 40-person team"],
    },
    fa: {
      title: "MRM",
      eyebrow: "ابزار تداوم کسب و کار · ۱۴۰۴",
      summary: "محصولی عملی برای روزهایی که اینترنت قطع بود.",
      short: "سامانه ای برای هماهنگی آفلاین که هنگام قطع اینترنت در شرایط جنگ، کار یک شرکت ۴۰ نفره را ادامه داد.",
      role: "مالک محصول · طراح · توسعه دهنده",
      problem: "در روزهای اول جنگ در ایران، دسترسی به اینترنت از بین رفت و ابزارهای ابری شرکت قابل استفاده نبودند. کار متوقف شده بود چون خود هماهنگی هم به اینترنت وابسته بود.",
      approach: "مسئله را به نیازهای عملیاتی ضروری کاهش دادم و ابزاری روی شبکه محلی ساختم که به اینترنت عمومی وابسته نبود. اولویت، تداوم کار و استفاده آسان بود نه تعداد زیاد امکانات.",
      result: "حدود ۴۰ نفر در دوره قطع اینترنت تا زمان بازگشت اتصال از MRM استفاده کردند و کارهای ضروری شرکت ادامه پیدا کرد.",
      metrics: ["حدود ۴۰ کاربر", "ساخته شده هنگام قطعی", "فعال روی شبکه محلی", "استفاده تا بازگشت اینترنت"],
      decisions: [
        ["محدوده بر اساس محدودیت واقعی", "هر قابلیت باید به یک سوال پاسخ می داد: آیا بدون اینترنت به ادامه کار تیم کمک می کند؟"],
        ["آشنایی به جای پیچیدگی", "در شرایط فشار، پذیرش ابزار مهم تر از امکانات پیشرفته است؛ تعامل ها مستقیم و قابل تشخیص ماندند."],
        ["تاب آوری محلی", "مسیر اصلی هماهنگی دیگر به در دسترس بودن سرویس های ابری وابسته نبود."],
      ],
      contribution: ["تعریف مسئله زیر فشار عملیاتی", "طراحی سریع محدوده و جریان کار", "ساخت کامل محصول", "راه اندازی و پذیرش در یک تیم ۴۰ نفره"],
    },
  },
  "first-choice": {
    accent: "red",
    images: [],
    en: {
      title: "First Choice",
      eyebrow: "Multilingual property platform",
      summary: "A clearer property journey across languages and markets.",
      short: "A multilingual real-estate experience shaped around discovery, comparison, and lead conversion.",
      role: "Product & Frontend Lead",
      problem: "Property discovery becomes harder when listings, buyer expectations, and sales operations cross languages and markets.",
      approach: "I shaped the experience around scannable listings, clear decision information, multilingual UX, and a direct route from browsing to a qualified inquiry.",
      result: "A coherent customer-facing product that connected property presentation, search, and conversion within one responsive experience.",
      metrics: ["Multilingual UX", "Responsive frontend", "Discovery-to-lead flow", "Reusable interface system"],
      decisions: [["Decision information first", "The interface prioritizes what buyers need to compare and act, rather than treating each property page as a decorative brochure."], ["Localization as product design", "Language support is part of layout, hierarchy, and content behavior, not a translation added at the end."]],
      contribution: ["Product and UX direction", "Responsive frontend architecture", "Multilingual interaction design", "Search, listing, and inquiry flows"],
    },
    fa: {
      title: "First Choice",
      eyebrow: "پلتفرم چندزبانه املاک",
      summary: "مسیر ساده تر انتخاب ملک در چند زبان و بازار.",
      short: "تجربه چندزبانه املاک با تمرکز بر جست وجو، مقایسه و تبدیل بازدیدکننده به سرنخ فروش.",
      role: "رهبر محصول و فرانت اند",
      problem: "وقتی فایل ها، انتظار خریدار و عملیات فروش میان چند زبان و بازار قرار می گیرند، پیدا کردن و مقایسه ملک سخت تر می شود.",
      approach: "تجربه را بر پایه فایل های قابل اسکن، اطلاعات روشن برای تصمیم گیری، رابط چندزبانه و مسیر مستقیم از مشاهده تا درخواست طراحی کردم.",
      result: "محصولی یکپارچه و واکنش گرا که معرفی ملک، جست وجو و تبدیل کاربر را در یک تجربه منسجم کنار هم قرار داد.",
      metrics: ["تجربه چندزبانه", "فرانت اند واکنش گرا", "مسیر کشف تا سرنخ", "سیستم رابط قابل استفاده مجدد"],
      decisions: [["اطلاعات تصمیم گیری در اولویت", "رابط به جای تبدیل صفحه ملک به بروشور تزئینی، اطلاعات لازم برای مقایسه و اقدام را جلوتر می آورد."], ["بومی سازی به عنوان طراحی محصول", "زبان بخشی از چیدمان، سلسله مراتب و رفتار محتواست؛ نه ترجمه ای که در پایان اضافه شود."]],
      contribution: ["جهت دهی محصول و تجربه کاربری", "معماری فرانت اند واکنش گرا", "طراحی تعامل چندزبانه", "جریان های جست وجو، فایل و درخواست"],
    },
  },
} as const;

export const projectSlugs = Object.keys(projects) as ProjectSlug[];
